apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathservice-deployment
  labels:
     app: mathservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mathservice
  template:
    metadata:
      labels:
        app: mathservice
    spec:
      containers:
        - name: mathservice
          image: irfanazam1/mathservice:be90e44
          ports:
            - containerPort: 8080
      hostNetwork: true
      dnsPolicy: Default
---
apiVersion: v1
kind: Service
metadata:
  name: mathservice
  labels:
    app: mathservice
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: mathservice
  type: LoadBalancer